# Generated by Django 4.1.1 on 2022-09-16 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMode',
            new_name='Profile',
        ),
    ]
